"""empty message

Revision ID: 0c39c92bc8b7
Revises: b939af34c619
Create Date: 2021-02-23 16:27:57.631880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c39c92bc8b7'
down_revision = 'b939af34c619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('placeholder', sa.String(length=1000), nullable=False))
    op.drop_column('fields', 'resume_html')
    op.drop_column('fields', 'form_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('form_html', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('fields', sa.Column('resume_html', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('fields', 'placeholder')
    # ### end Alembic commands ###
